# Generated by Django 4.2.3 on 2023-07-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0005_rename_comment_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="date",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
