# Generated by Django 4.2.3 on 2023-08-16 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0003_follows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follows",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="follows",
            name="user_follows",
        ),
        migrations.AddField(
            model_name="follows",
            name="user_follows",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
