# Generated by Django 4.2.3 on 2023-08-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0004_alter_follows_user_remove_follows_user_follows_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="follows",
            constraint=models.UniqueConstraint(
                fields=("user", "user_follows"), name="unique_follow"
            ),
        ),
    ]
