# Generated by Django 4.2.3 on 2023-08-21 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0008_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likes",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_like",
                to="network.post",
            ),
        ),
    ]
