# Generated by Django 4.2.3 on 2023-08-21 18:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0011_delete_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="users_like",
            field=models.ManyToManyField(
                related_name="users_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
