# Generated by Django 4.2.3 on 2023-07-11 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_alter_auction_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="categorie",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="categorie",
                to="auctions.categorie",
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="winning_user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="winning_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
