# Generated by Django 4.2.3 on 2023-07-12 17:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_watchlist_comment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Comments",
        ),
    ]
