# Generated by Django 4.2.3 on 2023-08-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0005_follows_unique_follow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
