# Generated by Django 4.2.3 on 2023-08-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("network", "0007_remove_post_likes_likes_likes_unique_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.PositiveIntegerField(default="0"),
        ),
    ]
